background_atmos: bundle exec ruby app/background_atmos
background_hoops_indonesia: bundle exec ruby app/background_hoops_indonesia
background_hoops_point: bundle exec ruby app/background_hoops_point
background_invincible_id: bundle exec ruby app/background_invincible_id
background_our_daily_dose: bundle exec ruby app/background_our_daily_dose