#!/usr/bin/env ruby
# frozen_string_literal: true

require './lib/sneaker_watcher_bot'

scraper_class = Service::Scraper::Atmos::DetectCollectionsChange
interval_seconds = scraper_class.interval_seconds
background_name = scraper_class.klass_tag.join('_')
EndlessLoop.perform(interval_seconds, background_name) { scraper_class.call }

Process.waitall
