#!/usr/bin/env ruby
# frozen_string_literal: true

require './lib/sneaker_watcher_bot'

Service::Scraper::Base.descendants.each do |scraper_class|
  if scraper_class.name.downcase =~ /instagram/
    # using fork process for better concurrencies
    fork do
      interval_seconds = scraper_class.interval_seconds
      background_name = scraper_class.klass_tag.join('_')
      EndlessLoop.perform(interval_seconds, background_name) { scraper_class.call }
    end
  end
end

Process.waitall