#!/usr/bin/env ruby
# frozen_string_literal: true

require './lib/sneaker_watcher_bot'

scraper_classes = [
  Service::Scraper::Nike::DetectSnkrsChange,
  Service::Scraper::Nike::DetectSnkrsReminder,
  Service::Scraper::OurDailyDose::DetectLatestChange,
  Service::Scraper::SeekIndonesia::DetectNewArrivalsChange,
  Service::Scraper::Zalora::DetectNikeChange
]

scraper_classes.each do |scraper_class|
  # skip instagram scrapers
  next if scraper_class.name.downcase =~ /instagram/

  # using fork process for better concurrencies
  fork do
    interval_seconds = scraper_class.interval_seconds
    background_name = scraper_class.klass_tag.join('_')
    EndlessLoop.perform(interval_seconds, background_name) { scraper_class.call }
  end
end

Process.waitall